image: onaio/python:2.7
env:
    - GOPATH=/var/cache/drone
services:
    - onaio/postgis
script:
    - psql -c "CREATE USER wkcdd WITH PASSWORD 'wkcdd';" -h 127.0.0.1 -U postgres postgres
    - psql -c "CREATE DATABASE wkcdd_test OWNER wkcdd;" -h 127.0.0.1 -U postgres postgres
